- name: install nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key 

- name: add nodejs apt repo
  apt_repository:
    repo: "{{item}}"
  loop: 
    - "deb https://deb.nodesource.com/node_{{node_repo_version}} {{ansible_distribution_release}} main"
    - "deb-src https://deb.nodesource.com/node_{{node_repo_version}} {{ansible_distribution_release}} main"

- name: install nodejs and npm
  apt:
    pkg: nodejs
