- name: add systemd service unit files
  template:
    src: systemd-unit.j2
    dest: "/etc/systemd/system/{{ item.prog }}.service"
  vars:
    service: "{{ item.name }}"
    bin_path: "{{ source_bin_dir }}/{{ item.prog }}"
  loop:
    - {name: "CWMP", prog: "genieacs-cwmp"}
    - {name: "EXT", prog: "genieacs-ext"}
    - {name: "FS", prog: "genieacs-fs"}
    - {name: "NBI", prog: "genieacs-nbi"}
    - {name: "UI", prog: "genieacs-ui"}
  notify: systemd daemon reload

- name: enable genieacs services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop: "{{ enabled_services }}"
